import { beforeEach, describe, expect, it, vi } from 'vitest';

const createDocMock = () => ({
    internal: {
        pageSize: {
            getWidth: () => 210,
            getHeight: () => 297,
        },
        getNumberOfPages: () => 1,
    },
    splitTextToSize: (text) => [String(text)],
    setFont: vi.fn(),
    setFontSize: vi.fn(),
    setTextColor: vi.fn(),
    text: vi.fn(),
    addImage: vi.fn(),
    addPage: vi.fn(),
    setPage: vi.fn(),
    setFillColor: vi.fn(),
    setDrawColor: vi.fn(),
    rect: vi.fn(),
    roundedRect: vi.fn(),
    circle: vi.fn(),
    path: vi.fn(),
    fill: vi.fn(),
    line: vi.fn(),
    save: vi.fn(),
});

let docMock;

vi.mock('jspdf', () => ({
    default: vi.fn(function MockJsPDF() {
        return docMock;
    }),
}));

describe('pdfGenerator', () => {
    beforeEach(() => {
        docMock = createDocMock();
        global.fetch = vi.fn().mockResolvedValue({
            ok: true,
            blob: async () => new Blob(['mock-image'], { type: 'image/jpeg' }),
        });

        class MockFileReader {
            constructor() {
                this.result = 'data:image/jpeg;base64,mock-image';
                this.onloadend = null;
                this.onerror = null;
            }

            readAsDataURL() {
                if (this.onloadend) {
                    this.onloadend({ target: { result: this.result } });
                }
            }
        }

        global.FileReader = MockFileReader;
    });

    it('includes remote scan images saved by URL and downloads the report', async () => {
        const { generatePDFReport } = await import('./pdfGenerator');

        await generatePDFReport(
            {
                image_url: 'https://example.com/tree.jpg',
                disease: 'Leaf Rust',
                healthStatus: 'unhealthy',
                severity: 'moderate',
                plantType: 'Durian',
                category: 'Fruits',
                description: 'Detected on lower leaves',
                symptoms: ['Rust spots'],
                treatments: ['Apply fungicide'],
            },
            'en',
            {
                en: {
                    common: {
                        dateLocale: 'en-MY',
                        locationNA: 'Location N/A',
                        page: 'Page',
                        of: 'of',
                        unknown: 'Unknown',
                        notAvailable: 'N/A',
                    },
                    pdf: {
                        title: 'Plant Analysis Report',
                        reportDate: 'Report date',
                        analysisDetails: 'Analysis Details',
                        treatmentPlan: 'Treatment Plan',
                        productRecommendations: 'Product Recommendations',
                        generatedBy: 'Generated by Agropreneur',
                    },
                    results: {
                        healthy: 'Healthy',
                        unhealthy: 'Unhealthy',
                        plantType: 'Plant Type',
                        category: 'Category',
                        scale: 'Scale',
                        diagnosis: 'Diagnosis',
                        fungusSpecies: 'Fungus Species',
                        pathogen: 'Pathogen',
                        aboutDisease: 'About',
                        symptoms: 'Symptoms',
                        treatments: 'Treatments',
                        immediateActions: 'Immediate Actions',
                        prevention: 'Prevention',
                        nutritionalIssues: 'Nutritional Issues',
                        diseaseControlProducts: 'Disease Control',
                        growthAndMaintenance: 'Growth & Maintenance',
                        fertilizersAndNutrition: 'Fertilizers & Nutrition',
                        recommendedSupplements: 'Recommended Supplements',
                    },
                    home: {
                        categoryFruits: 'Fruits',
                    },
                },
            },
        );

        expect(global.fetch).toHaveBeenCalledWith('https://example.com/tree.jpg', { mode: 'cors' });
        expect(docMock.addImage).toHaveBeenCalled();
        expect(docMock.save).toHaveBeenCalledWith(expect.stringMatching(/^plant-analysis-durian-/));
    });

    it('prefers live product recommendations passed in from the results screen', async () => {
        const { generatePDFReport } = await import('./pdfGenerator');

        await generatePDFReport(
            {
                disease: 'Leaf Rust',
                healthStatus: 'unhealthy',
                severity: 'moderate',
                plantType: 'Durian',
                category: 'Fruits',
                description: 'Detected on lower leaves',
                symptoms: ['Rust spots'],
                treatments: ['Apply fungicide'],
            },
            'en',
            {
                en: {
                    common: {
                        dateLocale: 'en-MY',
                        locationNA: 'Location N/A',
                        page: 'Page',
                        of: 'of',
                        unknown: 'Unknown',
                        notAvailable: 'N/A',
                    },
                    pdf: {
                        title: 'Plant Analysis Report',
                        reportDate: 'Report date',
                        analysisDetails: 'Analysis Details',
                        treatmentPlan: 'Treatment Plan',
                        productRecommendations: 'Product Recommendations',
                        generatedBy: 'Generated by Agropreneur',
                    },
                    results: {
                        healthy: 'Healthy',
                        unhealthy: 'Unhealthy',
                        plantType: 'Plant Type',
                        category: 'Category',
                        scale: 'Scale',
                        diagnosis: 'Diagnosis',
                        fungusSpecies: 'Fungus Species',
                        pathogen: 'Pathogen',
                        aboutDisease: 'About',
                        symptoms: 'Symptoms',
                        treatments: 'Treatments',
                        immediateActions: 'Immediate Actions',
                        prevention: 'Prevention',
                        nutritionalIssues: 'Nutritional Issues',
                        diseaseControlProducts: 'Disease Control',
                        growthAndMaintenance: 'Growth & Maintenance',
                        fertilizersAndNutrition: 'Fertilizers & Nutrition',
                        recommendedSupplements: 'Recommended Supplements',
                        fallbackProductsTitle: 'Fallback Store Suggestions',
                        fallbackProductsLabel: 'Fallback products',
                        otherPopular: 'Other Popular Products',
                    },
                    home: {
                        categoryFruits: 'Fruits',
                    },
                },
            },
            {
                productRecommendations: {
                    diseaseControl: [
                        {
                            id: 123,
                            name: 'Live Copper Fungicide',
                            description: 'Direct-match store product',
                            price: '54.00',
                        },
                    ],
                    fertilizers: [],
                    supplements: [],
                    otherPopular: [],
                    fallbackMeta: null,
                },
            },
        );

        expect(docMock.save).toHaveBeenCalledWith(expect.stringMatching(/^plant-analysis-durian-/));
    });

    it('does not fall back to static product data when live recommendations are explicitly unavailable', async () => {
        const { generatePDFReport } = await import('./pdfGenerator');

        await generatePDFReport(
            {
                disease: 'Leaf Rust',
                healthStatus: 'unhealthy',
                severity: 'moderate',
                plantType: 'Durian',
                category: 'Fruits',
                description: 'Detected on lower leaves',
                symptoms: ['Rust spots'],
                treatments: ['Apply fungicide'],
            },
            'en',
            {
                en: {
                    common: {
                        dateLocale: 'en-MY',
                        locationNA: 'Location N/A',
                        page: 'Page',
                        of: 'of',
                        unknown: 'Unknown',
                        notAvailable: 'N/A',
                    },
                    pdf: {
                        title: 'Plant Analysis Report',
                        reportDate: 'Report date',
                        analysisDetails: 'Analysis Details',
                        treatmentPlan: 'Treatment Plan',
                        productRecommendations: 'Product Recommendations',
                        generatedBy: 'Generated by Agropreneur',
                    },
                    results: {
                        healthy: 'Healthy',
                        unhealthy: 'Unhealthy',
                        plantType: 'Plant Type',
                        category: 'Category',
                        scale: 'Scale',
                        diagnosis: 'Diagnosis',
                        fungusSpecies: 'Fungus Species',
                        pathogen: 'Pathogen',
                        aboutDisease: 'About',
                        symptoms: 'Symptoms',
                        treatments: 'Treatments',
                        immediateActions: 'Immediate Actions',
                        prevention: 'Prevention',
                        nutritionalIssues: 'Nutritional Issues',
                        diseaseControlProducts: 'Disease Control',
                        growthAndMaintenance: 'Growth & Maintenance',
                        fertilizersAndNutrition: 'Fertilizers & Nutrition',
                        recommendedSupplements: 'Recommended Supplements',
                    },
                    home: {
                        categoryFruits: 'Fruits',
                    },
                },
            },
            {
                productRecommendations: null,
            },
        );

        expect(docMock.save).toHaveBeenCalledWith(expect.stringMatching(/^plant-analysis-durian-/));
    });

    it('does not render any product block when no live recommendations are provided', async () => {
        const { generatePDFReport } = await import('./pdfGenerator');

        await generatePDFReport(
            {
                disease: 'Leaf Rust',
                healthStatus: 'unhealthy',
                severity: 'moderate',
                plantType: 'Durian',
                category: 'Fruits',
                description: 'Detected on lower leaves',
                symptoms: ['Rust spots'],
                treatments: ['Apply fungicide'],
            },
            'en',
            {
                en: {
                    common: {
                        dateLocale: 'en-MY',
                        locationNA: 'Location N/A',
                        page: 'Page',
                        of: 'of',
                        unknown: 'Unknown',
                        notAvailable: 'N/A',
                    },
                    pdf: {
                        title: 'Plant Analysis Report',
                        reportDate: 'Report date',
                        analysisDetails: 'Analysis Details',
                        treatmentPlan: 'Treatment Plan',
                        productRecommendations: 'Product Recommendations',
                        generatedBy: 'Generated by Agropreneur',
                    },
                    results: {
                        healthy: 'Healthy',
                        unhealthy: 'Unhealthy',
                        plantType: 'Plant Type',
                        category: 'Category',
                        scale: 'Scale',
                        diagnosis: 'Diagnosis',
                        fungusSpecies: 'Fungus Species',
                        pathogen: 'Pathogen',
                        aboutDisease: 'About',
                        symptoms: 'Symptoms',
                        treatments: 'Treatments',
                        immediateActions: 'Immediate Actions',
                        prevention: 'Prevention',
                        nutritionalIssues: 'Nutritional Issues',
                    },
                    home: {
                        categoryFruits: 'Fruits',
                    },
                },
            },
        );

        expect(docMock.save).toHaveBeenCalledWith(expect.stringMatching(/^plant-analysis-durian-/));
    });
});
