const pdfTranslations = {
    "en": {
        "pdf": {
            "title": "Plant Health Analysis Report",
            "generatedBy": "Generated by Smart Plant Diseases & Advisor",
            "reportDate": "Report Date",
            "analysisDetails": "Analysis Details",
            "healthStatus": "Health Status",
            "diagnosis": "Diagnosis",
            "treatmentPlan": "Treatment Plan",
            "productRecommendations": "Product Recommendations",
            "supplierInformation": "Supplier Information",
            "disclaimer": "This report is generated automatically and should be used as a guide. Consult with agricultural experts for critical decisions."
        }
    },
    "ms": {
        "pdf": {
            "title": "Laporan Analisis Kesihatan Tumbuhan",
            "generatedBy": "Dijana oleh Smart Plant Diseases & Advisor",
            "reportDate": "Tarikh Laporan",
            "analysisDetails": "Butiran Analisis",
            "healthStatus": "Status Kesihatan",
            "diagnosis": "Diagnosis",
            "treatmentPlan": "Pelan Rawatan",
            "productRecommendations": "Cadangan Produk",
            "supplierInformation": "Maklumat Pembekal",
            "disclaimer": "Laporan ini dijana oleh sistem automatik dan harus digunakan sebagai panduan. Rujuk pakar pertanian untuk keputusan kritikal."
        }
    },
    "zh": {
        "pdf": {
            "title": "植物健康分析报告",
            "generatedBy": "由智能植物病害顾问生成",
            "reportDate": "报告日期",
            "analysisDetails": "分析详情",
            "healthStatus": "健康状态",
            "diagnosis": "诊断",
            "treatmentPlan": "治疗计划",
            "productRecommendations": "产品推荐",
            "supplierInformation": "供应商信息",
            "disclaimer": "此报告由系统自动生成，仅供参考。如需做出重要决策，请咨询专业农业专家。"
        }
    }
};

export default pdfTranslations;
