const pdfTranslations = {
    "en": {
        "pdf": {
            "title": "Plant Health Analysis Report",
            "generatedBy": "Generated by KANB Agropreneur Nasional",
            "reportDate": "Report Date",
            "analysisDetails": "Analysis Details",
            "healthStatus": "Health Status",
            "diagnosis": "Diagnosis",
            "treatmentPlan": "Treatment Plan",
            "productRecommendations": "Product Recommendations",
            "supplierInformation": "Supplier Information",
            "fieldDecisionSummary": "Field Decision Summary",
            "fieldUseNotice": "Field Use Notice",
            "fieldUseNoticeBody": "This report is a decision-support summary, not a laboratory diagnosis. Use it together with field inspection, local agronomy advice, and Malaysian product-label requirements before treatment.",
            "disclaimer": "This report is generated automatically and should be used as a guide. Consult with agricultural experts for critical decisions."
        }
    },
    "ms": {
        "pdf": {
            "title": "Laporan Analisis Kesihatan Tumbuhan",
            "generatedBy": "Dijana oleh KANB Agropreneur Nasional",
            "reportDate": "Tarikh Laporan",
            "analysisDetails": "Butiran Analisis",
            "healthStatus": "Status Kesihatan",
            "diagnosis": "Diagnosis",
            "treatmentPlan": "Pelan Rawatan",
            "productRecommendations": "Cadangan Produk",
            "supplierInformation": "Maklumat Pembekal",
            "fieldDecisionSummary": "Ringkasan Keputusan Lapangan",
            "fieldUseNotice": "Notis Penggunaan Lapangan",
            "fieldUseNoticeBody": "Laporan ini ialah ringkasan sokongan keputusan, bukan diagnosis makmal. Gunakan bersama pemeriksaan lapangan, nasihat agronomi setempat, dan keperluan label produk Malaysia sebelum rawatan.",
            "disclaimer": "Laporan ini dijana oleh sistem automatik dan harus digunakan sebagai panduan. Rujuk pakar pertanian untuk keputusan kritikal."
        }
    },
    "zh": {
        "pdf": {
            "title": "植物健康分析报告",
            "generatedBy": "由 KANB Agropreneur Nasional 生成",
            "reportDate": "报告日期",
            "analysisDetails": "分析详情",
            "healthStatus": "健康状态",
            "diagnosis": "诊断",
            "treatmentPlan": "处理方案",
            "productRecommendations": "产品推荐",
            "supplierInformation": "供应商信息",
            "fieldDecisionSummary": "田间判断摘要",
            "fieldUseNotice": "田间使用提示",
            "fieldUseNoticeBody": "本报告是决策辅助摘要，并非实验室诊断。处理前请结合田间检查、当地农艺建议，并遵守马来西亚产品标签要求。",
            "disclaimer": "本报告由系统生成，仅供参考。做出关键决定前，请咨询专业农业人员。"
        }
    }
};

export default pdfTranslations;
