export const scanQualityCopy = {
    en: { inconclusive: 'No clear diagnosis yet', sourceLanguageNotice: 'Some saved diagnosis text is in its original language. Interface labels follow your selection.', healthy: 'Healthy', unhealthy: 'Needs attention', critical: 'Critical', mild: 'Low', moderate: 'Moderate', severe: 'High', scanDetails: 'Scan details', viewHistory: 'View history',
        observations: 'What the photos show', limits: 'What remains uncertain', next: 'Next step',
        higherConfidence: 'Higher-confidence finding', nextChecks: 'Next checks',
        scoreNote: 'Model scores are estimates, not measured diagnostic accuracy.',
        noEvidence: 'The stored result does not include specific visual evidence.',
        nextRetake: 'Retake a sharp, well-lit photo of the affected area, including a close-up and a whole-plant view.',
        nextScout: 'Field scouting: verify the visible signs and possible alternatives before selecting treatment.',
        nextTreat: 'Review the suggested actions against field signs. Select the actual activity and product before recording treatment.',
        nextHealthy: 'Continue routine care and check for changes at the next inspection.',
        linkedScan: 'Linked scan', crop: 'Crop', status: 'Status', severity: 'Severity', location: 'Location',
        primary: 'Likely issue', symptoms: 'Observed symptoms', actions: 'Suggested immediate actions',
        plantPart: 'Photo subject', leaf: 'Leaf', fruit: 'Fruit', stem: 'Stem', whole: 'Whole plant',
        duration: 'How long have symptoms been present?', affected: 'Which parts or how much of the plant is affected?',
        recentTreatment: 'Recent treatment or fertilizer', contextTitle: 'Optional field context',
        plot: 'Plot', noPlot: 'No plot selected', followUp: 'Follow-up check',
        date: 'Next check date', outcome: 'Current outcome', pending: 'Not checked yet', improving: 'Improving',
        unchanged: 'Unchanged', worsening: 'Worsening', resolved: 'Resolved', save: 'Save follow-up',
        saved: 'Follow-up saved', failed: 'Could not save. Your changes are still shown; please retry.',
        photoGuidance: {
            title: 'Take clearer plant photos',
            intro: 'Good lighting and visible detail help us assess the plant more reliably.',
            wholeTitle: 'Whole-plant view',
            wholeHint: 'Show the plant and its surroundings so the affected area has context.',
            closeUpTitle: 'Affected-area close-up',
            closeUpHint: 'Fill the frame with the affected leaf, fruit, stem, or plant part.',
            tipsTitle: 'Before you capture',
            tips: ['Use soft daylight and avoid glare or deep shadows.', 'Hold the phone steady and tap the affected area to focus.', 'Keep the plant centered and remove distracting objects.'],
            retakeTitle: 'Retake this photo',
            issues: { IMAGE_TOO_DARK: 'Move into diffuse daylight and avoid placing the plant in front of a bright light.', IMAGE_TOO_BLURRY: 'Hold the phone steady, tap to focus, and keep the plant still.', IMAGE_TOO_LITTLE_LEAF: 'Move closer so the affected area fills more of the frame.', IMAGE_NOT_PLANT: 'Center the plant and remove background clutter, then try again.', LOW_IMAGE_QUALITY: 'Retake the photo with the plant centered, sharp, and well lit.' },
            dismiss: 'Dismiss photo tip',
            noIssue: 'Use both a whole-plant view and a sharp close-up when possible.',
        },
        comparison: { title: 'Compare scan and follow-up', select: 'Choose a follow-up check', original: 'Original scan', latest: 'Selected follow-up', summary: 'Change summary', noHistory: 'Save a follow-up check to compare changes over time.', noPhoto: 'No photo saved for this record', diagnosis: 'Diagnosis', health: 'Health state', symptoms: 'Reported symptoms', severity: 'Severity', recorded: 'Recorded', reportedNotes: 'Reported symptoms / field notes', outcome: 'Outcome', severityChange: 'Severity change', improved: 'Improved', worsened: 'Worsened', unchangedSeverity: 'Unchanged', notRecorded: 'Not recorded', noInference: 'This comparison shows reported changes and photos. It does not confirm a diagnosis or cure.' },
    },
    ms: { inconclusive: 'Diagnosis belum jelas', sourceLanguageNotice: 'Sebahagian teks diagnosis tersimpan masih dalam bahasa asal. Label antara muka mengikut pilihan anda.', healthy: 'Sihat', unhealthy: 'Perlu perhatian', critical: 'Kritikal', mild: 'Rendah', moderate: 'Sederhana', severe: 'Tinggi', scanDetails: 'Butiran imbasan', viewHistory: 'Lihat sejarah',
        observations: 'Apa yang ditunjukkan oleh foto', limits: 'Perkara yang belum pasti', next: 'Langkah seterusnya',
        higherConfidence: 'Penemuan dengan keyakinan lebih tinggi', nextChecks: 'Pemeriksaan seterusnya',
        scoreNote: 'Skor model ialah anggaran, bukan ukuran ketepatan diagnosis.',
        noEvidence: 'Keputusan tersimpan tidak mengandungi bukti visual khusus.',
        nextRetake: 'Ambil semula foto kawasan terjejas yang jelas dan terang, termasuk foto dekat dan keseluruhan pokok.',
        nextScout: 'Pemeriksaan lapangan: sahkan tanda yang kelihatan dan kemungkinan lain sebelum memilih rawatan.',
        nextTreat: 'Semak tindakan yang dicadangkan dengan tanda di lapangan. Pilih aktiviti dan produk sebenar sebelum merekodkan rawatan.',
        nextHealthy: 'Teruskan penjagaan rutin dan periksa perubahan pada pemeriksaan seterusnya.',
        linkedScan: 'Imbasan berkaitan', crop: 'Tanaman', status: 'Status', severity: 'Tahap keterukan', location: 'Lokasi',
        primary: 'Masalah yang disyaki', symptoms: 'Gejala yang diperhatikan', actions: 'Tindakan segera yang dicadangkan',
        plantPart: 'Subjek foto', leaf: 'Daun', fruit: 'Buah', stem: 'Batang', whole: 'Keseluruhan pokok',
        duration: 'Berapa lama gejala telah kelihatan?', affected: 'Bahagian atau jumlah pokok yang terjejas?',
        recentTreatment: 'Rawatan atau baja terkini', contextTitle: 'Konteks lapangan pilihan',
        plot: 'Plot', noPlot: 'Tiada plot dipilih', followUp: 'Pemeriksaan susulan',
        date: 'Tarikh pemeriksaan seterusnya', outcome: 'Keadaan semasa', pending: 'Belum diperiksa', improving: 'Bertambah baik',
        unchanged: 'Tiada perubahan', worsening: 'Bertambah teruk', resolved: 'Pulih', save: 'Simpan susulan',
        saved: 'Susulan disimpan', failed: 'Tidak dapat disimpan. Perubahan masih dipaparkan; sila cuba lagi.',
        photoGuidance: {
            title: 'Ambil foto pokok yang lebih jelas',
            intro: 'Cahaya yang baik dan butiran yang jelas membantu kami menilai pokok dengan lebih tepat.',
            wholeTitle: 'Pandangan keseluruhan pokok',
            wholeHint: 'Tunjukkan pokok dan persekitarannya supaya bahagian terjejas mempunyai konteks.',
            closeUpTitle: 'Foto dekat bahagian terjejas',
            closeUpHint: 'Penuhi bingkai dengan daun, buah, batang atau bahagian pokok yang terjejas.',
            tipsTitle: 'Sebelum mengambil foto',
            tips: ['Gunakan cahaya siang lembut dan elakkan silau atau bayang gelap.', 'Pegang telefon dengan stabil dan sentuh bahagian terjejas untuk fokus.', 'Letakkan pokok di tengah dan alihkan objek yang mengganggu.'],
            retakeTitle: 'Ambil semula foto ini',
            issues: { IMAGE_TOO_DARK: 'Beralih ke cahaya siang lembut dan jangan letakkan pokok di hadapan cahaya terang.', IMAGE_TOO_BLURRY: 'Pegang telefon dengan stabil, sentuh untuk fokus dan jangan gerakkan pokok.', IMAGE_TOO_LITTLE_LEAF: 'Dekatkan telefon supaya bahagian terjejas memenuhi lebih banyak ruang.', IMAGE_NOT_PLANT: 'Letakkan pokok di tengah dan kurangkan gangguan latar sebelum mencuba lagi.', LOW_IMAGE_QUALITY: 'Ambil semula foto dengan pokok di tengah, jelas dan bercahaya baik.' },
            dismiss: 'Tutup petua foto',
            noIssue: 'Jika boleh, gunakan pandangan keseluruhan pokok dan foto dekat yang jelas.',
        },
        comparison: { title: 'Bandingkan imbasan dan susulan', select: 'Pilih pemeriksaan susulan', original: 'Imbasan asal', latest: 'Susulan dipilih', summary: 'Ringkasan perubahan', noHistory: 'Simpan pemeriksaan susulan untuk membandingkan perubahan dari masa ke masa.', noPhoto: 'Tiada foto disimpan untuk rekod ini', diagnosis: 'Diagnosis', health: 'Keadaan kesihatan', symptoms: 'Gejala yang dilaporkan', severity: 'Tahap keterukan', recorded: 'Direkodkan', reportedNotes: 'Gejala / nota lapangan yang dilaporkan', outcome: 'Keadaan semasa', severityChange: 'Perubahan tahap keterukan', improved: 'Bertambah baik', worsened: 'Bertambah teruk', unchangedSeverity: 'Tiada perubahan', notRecorded: 'Belum direkodkan', noInference: 'Perbandingan ini menunjukkan perubahan dan foto yang dilaporkan. Ia tidak mengesahkan diagnosis atau pemulihan.' },
    },
    zh: { inconclusive: '尚无法明确诊断', sourceLanguageNotice: '部分保存的诊断文字仍为原始语言。界面标签会使用您选择的语言。', healthy: '健康', unhealthy: '需要关注', critical: '严重危急', mild: '轻微', moderate: '中等', severe: '严重', scanDetails: '扫描详情', viewHistory: '查看历史',
        observations: '照片显示的迹象', limits: '尚不确定的事项', next: '下一步',
        higherConfidence: '证据较充分的判断', nextChecks: '下一步检查',
        scoreNote: '模型分数仅为估计，并非经过验证的诊断准确率。',
        noEvidence: '保存的结果未包含具体视觉证据。',
        nextRetake: '重新拍摄患部清晰且光线充足的照片，同时提供特写和整株照片。',
        nextScout: '田间检查：选择处理措施前，先核实可见迹象和其他可能原因。',
        nextTreat: '结合田间迹象核实建议。记录处理前，请选择实际操作和产品。',
        nextHealthy: '继续日常养护，并在下次检查时留意变化。',
        linkedScan: '关联扫描', crop: '作物', status: '状态', severity: '严重程度', location: '位置',
        primary: '可能的问题', symptoms: '观察到的症状', actions: '建议立即采取的措施',
        plantPart: '照片主体', leaf: '叶片', fruit: '果实', stem: '茎干', whole: '整株',
        duration: '症状出现多久了？', affected: '哪些部位或多少植株受到影响？',
        recentTreatment: '近期处理或施肥', contextTitle: '选填田间信息',
        plot: '地块', noPlot: '未选择地块', followUp: '后续检查',
        date: '下次检查日期', outcome: '当前变化', pending: '尚未检查', improving: '正在好转',
        unchanged: '无变化', worsening: '正在恶化', resolved: '已恢复', save: '保存后续记录',
        saved: '后续记录已保存', failed: '无法保存。修改仍保留在页面中，请重试。',
        photoGuidance: {
            title: '拍摄更清晰的植物照片',
            intro: '良好的光线和清晰的细节有助于更可靠地评估植物。',
            wholeTitle: '整株照片',
            wholeHint: '展示植物及其周围环境，让受影响部位保留上下文。',
            closeUpTitle: '受影响部位特写',
            closeUpHint: '让受影响的叶片、果实、茎干或植物部位填满画面。',
            tipsTitle: '拍摄前检查',
            tips: ['使用柔和的日光，避免反光或深阴影。', '拿稳手机并点击受影响部位进行对焦。', '让植物居中并移开干扰背景的物体。'],
            retakeTitle: '重新拍摄这张照片',
            issues: { IMAGE_TOO_DARK: '移到柔和的日光下，避免让植物背对强光。', IMAGE_TOO_BLURRY: '拿稳手机，点击对焦，并保持植物不动。', IMAGE_TOO_LITTLE_LEAF: '靠近一些，让受影响部位占据更多画面。', IMAGE_NOT_PLANT: '让植物居中并减少背景干扰，然后重试。', LOW_IMAGE_QUALITY: '让植物居中、清晰且光线充足，然后重新拍摄。' },
            dismiss: '关闭拍摄提示',
            noIssue: '如果可以，请同时提供整株照片和清晰的受影响部位特写。',
        },
        comparison: { title: '比较扫描和后续检查', select: '选择后续检查', original: '原始扫描', latest: '所选后续记录', summary: '变化摘要', noHistory: '保存一次后续检查，即可比较一段时间内的变化。', noPhoto: '此记录没有保存照片', diagnosis: '诊断', health: '健康状态', symptoms: '报告的症状', severity: '严重程度', recorded: '记录时间', reportedNotes: '报告的症状 / 田间备注', outcome: '当前变化', severityChange: '严重程度变化', improved: '有所改善', worsened: '变得更严重', unchangedSeverity: '没有变化', notRecorded: '未记录', noInference: '此比较显示已报告的变化和照片，不能单独确认诊断或痊愈。' },
    },
};
export const getScanQualityCopy = (language) => scanQualityCopy[language] || scanQualityCopy.en;
