export const scanQualityCopy = {
    en: { healthy: 'Healthy', critical: 'Critical', mild: 'Low', moderate: 'Moderate', severe: 'High', scanDetails: 'Scan details', viewHistory: 'View history',
        observations: 'What the photos show', limits: 'What remains uncertain', next: 'Next step',
        higherConfidence: 'Higher-confidence finding', nextChecks: 'Next checks',
        scoreNote: 'Model scores are estimates, not measured diagnostic accuracy.',
        noEvidence: 'The stored result does not include specific visual evidence.',
        nextRetake: 'Retake a sharp, well-lit photo of the affected area, including a close-up and a whole-plant view.',
        nextScout: 'Field scouting: verify the visible signs and possible alternatives before selecting treatment.',
        nextTreat: 'Review the suggested actions against field signs. Select the actual activity and product before recording treatment.',
        nextHealthy: 'Continue routine care and check for changes at the next inspection.',
        linkedScan: 'Linked scan', crop: 'Crop', status: 'Status', severity: 'Severity', location: 'Location',
        primary: 'Likely issue', symptoms: 'Observed symptoms', actions: 'Suggested immediate actions',
        plantPart: 'Photo subject', leaf: 'Leaf', fruit: 'Fruit', stem: 'Stem', whole: 'Whole plant',
        duration: 'How long have symptoms been present?', affected: 'Which parts or how much of the plant is affected?',
        recentTreatment: 'Recent treatment or fertilizer', contextTitle: 'Optional field context',
        plot: 'Plot', noPlot: 'No plot selected', followUp: 'Follow-up check',
        date: 'Next check date', outcome: 'Current outcome', pending: 'Not checked yet', improving: 'Improving',
        unchanged: 'Unchanged', worsening: 'Worsening', resolved: 'Resolved', save: 'Save follow-up',
        saved: 'Follow-up saved', failed: 'Could not save. Your changes are still shown; please retry.',
    },
    ms: { healthy: 'Sihat', critical: 'Kritikal', mild: 'Rendah', moderate: 'Sederhana', severe: 'Tinggi', scanDetails: 'Butiran imbasan', viewHistory: 'Lihat sejarah',
        observations: 'Apa yang ditunjukkan oleh foto', limits: 'Perkara yang belum pasti', next: 'Langkah seterusnya',
        higherConfidence: 'Penemuan dengan keyakinan lebih tinggi', nextChecks: 'Pemeriksaan seterusnya',
        scoreNote: 'Skor model ialah anggaran, bukan ukuran ketepatan diagnosis.',
        noEvidence: 'Keputusan tersimpan tidak mengandungi bukti visual khusus.',
        nextRetake: 'Ambil semula foto kawasan terjejas yang jelas dan terang, termasuk foto dekat dan keseluruhan pokok.',
        nextScout: 'Pemeriksaan lapangan: sahkan tanda yang kelihatan dan kemungkinan lain sebelum memilih rawatan.',
        nextTreat: 'Semak tindakan yang dicadangkan dengan tanda di lapangan. Pilih aktiviti dan produk sebenar sebelum merekodkan rawatan.',
        nextHealthy: 'Teruskan penjagaan rutin dan periksa perubahan pada pemeriksaan seterusnya.',
        linkedScan: 'Imbasan berkaitan', crop: 'Tanaman', status: 'Status', severity: 'Tahap keterukan', location: 'Lokasi',
        primary: 'Masalah yang disyaki', symptoms: 'Gejala yang diperhatikan', actions: 'Tindakan segera yang dicadangkan',
        plantPart: 'Subjek foto', leaf: 'Daun', fruit: 'Buah', stem: 'Batang', whole: 'Keseluruhan pokok',
        duration: 'Berapa lama gejala telah kelihatan?', affected: 'Bahagian atau jumlah pokok yang terjejas?',
        recentTreatment: 'Rawatan atau baja terkini', contextTitle: 'Konteks lapangan pilihan',
        plot: 'Plot', noPlot: 'Tiada plot dipilih', followUp: 'Pemeriksaan susulan',
        date: 'Tarikh pemeriksaan seterusnya', outcome: 'Keadaan semasa', pending: 'Belum diperiksa', improving: 'Bertambah baik',
        unchanged: 'Tiada perubahan', worsening: 'Bertambah teruk', resolved: 'Pulih', save: 'Simpan susulan',
        saved: 'Susulan disimpan', failed: 'Tidak dapat disimpan. Perubahan masih dipaparkan; sila cuba lagi.',
    },
    zh: { healthy: '健康', critical: '严重危急', mild: '轻微', moderate: '中等', severe: '严重', scanDetails: '扫描详情', viewHistory: '查看历史',
        observations: '照片显示的迹象', limits: '尚不确定的事项', next: '下一步',
        higherConfidence: '证据较充分的判断', nextChecks: '下一步检查',
        scoreNote: '模型分数仅为估计，并非经过验证的诊断准确率。',
        noEvidence: '保存的结果未包含具体视觉证据。',
        nextRetake: '重新拍摄患部清晰且光线充足的照片，同时提供特写和整株照片。',
        nextScout: '田间检查：选择处理措施前，先核实可见迹象和其他可能原因。',
        nextTreat: '结合田间迹象核实建议。记录处理前，请选择实际操作和产品。',
        nextHealthy: '继续日常养护，并在下次检查时留意变化。',
        linkedScan: '关联扫描', crop: '作物', status: '状态', severity: '严重程度', location: '位置',
        primary: '可能的问题', symptoms: '观察到的症状', actions: '建议立即采取的措施',
        plantPart: '照片主体', leaf: '叶片', fruit: '果实', stem: '茎干', whole: '整株',
        duration: '症状出现多久了？', affected: '哪些部位或多少植株受到影响？',
        recentTreatment: '近期处理或施肥', contextTitle: '选填田间信息',
        plot: '地块', noPlot: '未选择地块', followUp: '后续检查',
        date: '下次检查日期', outcome: '当前变化', pending: '尚未检查', improving: '正在好转',
        unchanged: '无变化', worsening: '正在恶化', resolved: '已恢复', save: '保存后续记录',
        saved: '后续记录已保存', failed: '无法保存。修改仍保留在页面中，请重试。',
    },
};
export const getScanQualityCopy = (language) => scanQualityCopy[language] || scanQualityCopy.en;
